### ISSUE TITLE
breakout element is wider than screen

### ISSUE THREAD

**Issue by retosteffen** [LucidNinja/tailwind-container-break-out#5]
The breakout element is 5px or 15px wider than the screen depending on the breakpoint.
I'm using it in a vue3 project with tailwindcss/postcss7-compat@^2.2.17 and vue-cli 4.5.15. I believe it's related to postcss7-compat and will investigate but any hints would be welcome. As I'm not yet ready to update vue-cli to v5

**Comment by LucidNinja** [comment]
Hi - are you able to provide a working example in Codesandbox?

**Comment by retosteffen** [comment]
Hi,
I couldn't make it work on codesandbox but here is a github repo
https://github.com/retosteffen/vue-breakout-test

I figured out that it was because of the vertical scroll bar that pushed the container to the left.


<img width="1006" alt="Screenshot 2022-02-24 at 16 54 30" src="https://user-images.githubusercontent.com/1895562/155559611-1db3d6aa-041a-46d9-81b9-74e7cd68a8eb.png">

**Comment by LucidNinja** [comment]
What browser / OS are you using? I have got this up and running and can't replicate the issue. This could be related to #2?

**Comment by LucidNinja** [comment]
Unfortunately on a Windows machine (and maybe Linux?) the viewport width is calculated differently, depending if there are scrollbars. So this is something I will be looking into.

**Comment by retosteffen** [comment]
I'm on macOS and it's the same behavior in Chrome, Safari and Firefox.
I'll look into it more.

**Comment by LucidNinja** [comment]
Can you share any screen recordings or screenshots of the issue? Maybe with dev tools open too?

**Comment by LucidNinja** [comment]
Can I ask - do you have your scroll bars set to always visible in System Preferences > General?

**Comment by retosteffen** [comment]
Sure. Here is a couple of screenshots.
Scrollbars are set to show automatically.

Btw I tried to deploy a project including tailwind-container-break-out with forge and it failed to build:
```
-  Building for production...
 ERROR  Failed to compile with 1 error9:07:13 AM

 error  in ./src/assets/styles/index.css

/.../node_modules/tailwind-container-break-out/src/tailwind-container-break-out.js:29
  return normalizeScreens(Object.entries(screens ?? {}), false)
                                                  ^

SyntaxError: Unexpected token '?'
```


<img width="1086" alt="Screenshot 2022-03-04 at 11 40 44" src="https://user-images.githubusercontent.com/1895562/156749044-6f49258e-b155-47ea-b96b-9bc11b960740.png">
<img width="1081" alt="Screenshot 2022-03-04 at 11 41 02" src="https://user-images.githubusercontent.com/1895562/156749059-9080d53c-2402-4fdc-8c91-ce4f64d48d1f.png">
<img width="1196" alt="Screenshot 2022-03-04 at 11 43 08" src="https://user-images.githubusercontent.com/1895562/156749066-419b7caf-2e94-468e-aca1-9dcfac98453f.png">

**Comment by LucidNinja** [comment]
That’s super unusual. I’ll take another look. 

And yes, I came across the `Unexpected Token ?` error recently when deploying to Vercel. It’s actually because the package uses a nullish coallescing operator which is only supported on Node versions 14 and above. Can you confirm if you’re using <14.0? If so, can you change your node version or is that out of the question? I could potentially patch it to support older versions of Node.

**Comment by LucidNinja** [comment]
Can I ask - your second screenshot appears to be working correctly - is that right? Is there a difference with that one?

**Comment by retosteffen** [comment]
> Can I ask - your second screenshot appears to be working correctly - is that right? Is there a difference with that one?

Yes that's what I meant previously, it's because the content isn't bigger vertically than the page. As long as everything fits vertically there is no issue.

**Comment by retosteffen** [comment]
> That’s super unusual. I’ll take another look.
> 
> And yes, I came across the `Unexpected Token ?` error recently when deploying to Vercel. It’s actually because the package uses a nullish coallescing operator which is only supported on Node versions 14 and above. Can you confirm if you’re using <14.0? If so, can you change your node version or is that out of the question? I could potentially patch it to support older versions of Node.

Yes indeed that server is still on node v12.22.7. It should be ok to update, I'll check.

**Comment by LucidNinja** [comment]
I've managed to replicate the issue on a Mac by setting the scrollbars to show "Always". It's proving to be a tricky problem, however, because we might need to rely on some JS to get this to work. Unfortunately the solution mentioned here: https://github.com/LucidNinja/tailwind-container-break-out/issues/2#issue-1056396816 doesn't work for this use case. I'll have a think about a solution, but if you have any thoughts, I'm open to them.

**Comment by LucidNinja** [comment]
Ok, so my proposed solution is to use a variable inside of the package (`--twb-scrollbar-width`), which will be set to 0px by default. On it's own, this doesn't fix the problem, but perhaps I adjust the documentation to account for that, and then people would be required to add this bit of JS in their project manually, in order to set the `--twb-scrollbar-width` based on the browser. 

```
const setScrollbarWidth = () => {
  const prevWidth = window.getComputedStyle( document.documentElement ).getPropertyValue( '--twb-scrollbar-width' );
  const newWidth = `${ window.innerWidth - document.body.clientWidth }px`;
  
  if ( newWidth !== prevWidth ) {
    document.documentElement.style.setProperty( '--twb-scrollbar-width', newWidth );
  }
};

window.addEventListener( 'load', setScrollbarWidth );
window.addEventListener( 'resize', setScrollbarWidth );

setScrollbarWidth();
```

This doesn't solve the issue in this package alone, but it allows the developer opportunity for customisation and doesn't lock them into one JS framework.

Thoughts?

**Comment by LucidNinja** [comment]
I have updated this package to include a CSS variable `--twcb-scrollbar-width`, which is used in the calculation of the viewport width. This variable is set as 0px by default, so it needs to either be set by the developer using Javascript or by using this package: https://github.com/LucidNinja/set-scrollbar-width in tandem. I will close this issue for now, but if you foresee this as being problematic for your use case, please reach out.
